### ISSUE TITLE
Running on Mac OS

### ISSUE THREAD

**Issue by simonz21** [digital-dj-tools/dj-data-converter#8]
Am trying to follow the instructions on my Macbook, but every time I try and run the command it says command not recognised. Can any help?

**Comment by alzadude** [comment]
Hi @simonz21,

Thanks for you interest in the app. Can you attach a screenshot of the terminal window where you're trying to run the command, with the error message?

Thanks!

**Comment by timkirtley** [comment]
Was there ever a solution to this?  Running into the same issue, where when I run `dj-data-converter-macos` I just get `dj-data-converter-macos: command not found`

**Comment by alzadude** [comment]
> Was there ever a solution to this? Running into the same issue, where when I run `dj-data-converter-macos` I just get `dj-data-converter-macos: command not found`

Hi @timkirtley, this sounds like the file permissions issue #12; this was fixed in version 0.3.2, so if you download the latest .tar.gz archive for macos and extract it, the permissions should be set correctly and the command should work:

https://github.com/digital-dj-tools/dj-data-converter/releases/tag/0.3.4

I know this to be working from other users' feedback, so you should be ok 🙂

**Comment by timkirtley** [comment]
Hey thanks for the reply, I guess I'm doing something wrong?

Downloaded the .tar (https://github.com/digital-dj-tools/dj-data-converter/releases/download/0.3.4/dj-data-converter-macos.tar.gz)

Extracted it, opened Terminal, navigated to the folder with it in, and then type `dj-data-converter-macos`, but I still get the `dj-data-converter-macos: command not found` error 😢

**Comment by alzadude** [comment]
Hi @timkirtley,

I don't have a Mac, but I just did an experiment on Azure DevOps where the continuous build for the project runs (it provides Mac instances for testing purposes).

When I use `./dj-data-converter-macos`, the app runs. Without going into the details, the dot-slash prefix is required due to security restrictions for the `PATH` environment variable (at least for the bash shell, which I believe is the default on Mac and is therefore probably what you have). 

Could you try that instead?

If this works for you, I'll update the README and close this issue!

**Comment by timkirtley** [comment]
Hey, thats awesome yes that one works thanks so much for looking into it for me!
